## A   ██╗   ██╗███╗   ██╗██╗ ██████╗ ███╗   ██╗       ██████╗██████╗  █████╗ ██╗  ██╗   ██╗  ██╗██╗   ██╗███████╗
##     ██║   ██║████╗  ██║██║██╔═══██╗████╗  ██║      ██╔════╝██╔══██╗██╔══██╗╚██╗██╔╝   ╚██╗██╔╝╚██╗ ██╔╝╚══███╔╝
##     ██║   ██║██╔██╗ ██║██║██║   ██║██╔██╗ ██║█████╗██║     ██████╔╝███████║ ╚███╔╝     ╚███╔╝  ╚████╔╝   ███╔╝ 
##     ██║   ██║██║╚██╗██║██║██║   ██║██║╚██╗██║╚════╝██║     ██╔══██╗██╔══██║ ██╔██╗     ██╔██╗   ╚██╔╝   ███╔╝  
##     ╚██████╔╝██║ ╚████║██║╚██████╔╝██║ ╚████║      ╚██████╗██║  ██║██║  ██║██╔╝ ██╗██╗██╔╝ ██╗   ██║   ███████╗  game...
##      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝       ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ 
                                                                                                           
[Photon]
## Photon App IDs (if you wish to set up your own for private gorilla times, you may. this is just going to be the default.)
RealtimeAppId = fa353756-050a-42db-bf0c-88a2d29b4ef5 # this is my own realtimeappid and will default to it if either the ini is missing or this is blank.
PunAppId = 0f184139-4851-45d1-a250-9f062cdf121c # same thing for this one.
Region = us # i am from the us so the servers are based here too, i'm sorry

[PlayFab]
## PlayFab Title ID (veeanti's own playfab title, not the official one)
TitleId = 16F775

## PlayFab API URL
PlayFabUrl = https://16F775.playfabapi.com

[Steam]
## Steam App ID to spoof (1533390 for Gorilla Tag, should be set for 480 for Spacewar)
AppId = 480 # 480 will be the default if this is blank or missing. ...what? you don't like spacewar? well, that's too bad, because that's what you'll be spoofing as if you don't set this up. you can set it to 1533390 if you want to spoof as gorilla tag, but that might cause some... issues. so, you know, be careful with that one.

##                                                               __     _ 
##   this was made by...    _   __  ___   ___   ____ _   ____   / /_   (_)
##                         | | / / / _ \ / _ \ / __ `/  / __ \ / __/  / / 
##                         | |/ / /  __//  __// /_/ /  / / / // /_   / /  
##                         |___/  \___/ \___/ \__,_/  /_/ /_/ \__/  /_/      ...enjoy.                                               