# This workflow builds a BepInEx .NET plugin
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install BepInEx templates
      run: |
        dotnet new install BepInEx.Templates::2.0.0-be.4 --nuget-source https://nuget.bepinex.dev/v3/index.json

    - name: Restore dependencies
      run: dotnet restore GorillaCrack.csproj

    - name: Build
      run: dotnet build GorillaCrack.csproj -c Release --no-restore

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GorillaCrack
        path: bin/Release/netstandard2.1/GorillaCrack.dll